### ISSUE TITLE
App Crashes on SButton Press

### ISSUE THREAD

**Issue by Alberto96** [AndreiLux/Synapse#53]
```12:02:14.695 Error AndroidRuntime 5744  FATAL EXCEPTION: main
12:02:14.695 Error AndroidRuntime 5744  Process: com.af.synapse, PID: 5744
12:02:14.695 Error AndroidRuntime 5744  java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
12:02:14.695 Error AndroidRuntime 5744  	at com.af.synapse.elements.SButton.onClick(SButton.java:80)
12:02:14.695 Error AndroidRuntime 5744  	at android.view.View.performClick(View.java:4789)
12:02:14.695 Error AndroidRuntime 5744  	at android.view.View$PerformClick.run(View.java:19881)
12:02:14.695 Error AndroidRuntime 5744  	at android.os.Handler.handleCallback(Handler.java:739)
12:02:14.695 Error AndroidRuntime 5744  	at android.os.Handler.dispatchMessage(Handler.java:95)
12:02:14.695 Error AndroidRuntime 5744  	at android.os.Looper.loop(Looper.java:135)
12:02:14.695 Error AndroidRuntime 5744  	at android.app.ActivityThread.main(ActivityThread.java:5293)
12:02:14.695 Error AndroidRuntime 5744  	at java.lang.reflect.Method.invoke(Native Method)
12:02:14.695 Error AndroidRuntime 5744  	at java.lang.reflect.Method.invoke(Method.java:372)
12:02:14.695 Error AndroidRuntime 5744  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
12:02:14.695 Error AndroidRuntime 5744  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)```

Running CM12.1, with latest sources.

**Comment by AndreiLux** [comment]
Are you running mods that change the look of toast messages?

**Comment by Alberto96** [comment]
Nope, clean source-built CM12.1.

**Comment by AndreiLux** [comment]
... does CM12.1 then change the looks of default toast messages?

**Comment by Alberto96** [comment]
I highly doubt it.

**Comment by AndreiLux** [comment]
Not really helpful... The error is happening because the OS creates a toast message with a different layout container than what is on stock Android. I'll have a look to try to adapt it if this is something CM decided to change.

**Comment by Alberto96** [comment]
https://github.com/CyanogenMod/android_frameworks_base/commit/0d624b04b0b8d270bf59f564d739c312b7d2f07a

**Comment by AndreiLux** [comment]
Yea that's a shitty thing to do.

**Comment by AndreiLux** [comment]
https://www.dropbox.com/s/vwp1oc34ikspwe4/Synapse-release.apk?dl=0

Let me know if that fixes it.

**Comment by Alberto96** [comment]
Working Perfect :+1:

**Comment by Alberto96** [comment]
oops, wrong button pressed.
