### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kularny** [AndreiLux/Synapse#56]
```
03-22 11:37:49.592  4789  4937 W System.err: com.af.synapse.utils.ElementFailureException: com.af.synapse.utils.RunCommandFailedException: sed: Invalid argument
03-22 11:37:49.592  4789  4937 W System.err: 	at com.af.synapse.elements.SOptionList.getLiveValue(SOptionList.java:467)
03-22 11:37:49.592  4789  4937 W System.err: 	at com.af.synapse.elements.SOptionList.getView(SOptionList.java:185)
03-22 11:37:49.592  4789  4937 W System.err: 	at com.af.synapse.MainActivity$TabSectionFragment.prepareView(MainActivity.java:475)
03-22 11:37:49.592  4789  4937 W System.err: 	at com.af.synapse.MainActivity$TabSectionFragment.setArguments(MainActivity.java:509)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.MainActivity$SectionsPagerAdapter.buildFragment(MainActivity.java:348)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.MainActivity$SectionsPagerAdapter.access$600(MainActivity.java:340)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.MainActivity$SectionsPagerAdapter$2.run(MainActivity.java:385)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.utils.NamedRunnable.run(NamedRunnable.java:28)
03-22 11:37:49.593  4789  4937 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-22 11:37:49.593  4789  4937 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-22 11:37:49.593  4789  4937 W System.err: 	at java.lang.Thread.run(Thread.java:818)
03-22 11:37:49.593  4789  4937 W System.err: Caused by: com.af.synapse.utils.RunCommandFailedException: sed: Invalid argument
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.utils.SuperShell.flushError(Utils.java:341)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.utils.SuperShell.runCommand(Utils.java:385)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.utils.Utils.runCommandWithException(Utils.java:96)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.utils.Utils.runCommand(Utils.java:103)
03-22 11:37:49.593  4789  4937 W System.err: 	at com.af.synapse.elements.SOptionList.getLiveValue(SOptionList.java:464)
03-22 11:37:49.593  4789  4937 W System.err: 	... 10 more
```

It crashes on the I/O sched screen in M...In L, it works fine. Selinux is permissive.

https://github.com/kularny/GeniSys.Kernel/blob/smdk4210/Synapse/Synapse/synapse/config.json.generate.fs

**Comment by AndreiLux** [comment]
Not really caused by the app, your sed command is failing. Check if you have the proper busybox or whatever tools which support sed.

**Comment by kularny** [comment]
Doesn't work. I tried manually adding static_busybox in common.mk...then also without that I ran sed in terminal...it works. Definitely some other problem.

**Comment by AndreiLux** [comment]
It's an issue of your script or environment. The ```sed: Invalid argument``` part of the error comes directly from the error output stream of the shell, not from the app itself.

**Comment by kularny** [comment]
Yea ur correct.. Not an app bug... The script works fine on lollipop...for now il remove the json from generate...users  can use kernel auditor for io schedulers.
