### ISSUE TITLE
COMMAND CAUSING FCs

### ISSUE THREAD

**Issue by arny24x7** [AndreiLux/Synapse#61]
https://github.com/kularny/android_vendor_du/blob/m/prebuilt/common/Synapse/synapse/actions/reset-fuelgauge

This command is fcing the whole synapse app. In the earlier version, everything was working fine.

**Comment by arny24x7** [comment]
I also tried with the previous version. Works perfectly.

**Comment by AndreiLux** [comment]
If you can't post any more detailed description of the FC then I can't help you. The SButton element wasn't changed in over a year and a half.

**Comment by arny24x7** [comment]
```
--------- beginning of crash
09-18 18:52:42.177  5586  5586 E AndroidRuntime: FATAL EXCEPTION: main
09-18 18:52:42.177  5586  5586 E AndroidRuntime: Process: com.af.synapse, PID: 5586
09-18 18:52:42.177  5586  5586 E AndroidRuntime: Theme: themes:{}
09-18 18:52:42.177  5586  5586 E AndroidRuntime: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at com.af.synapse.elements.SButton.onClick(SButton.java:80)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at android.view.View.performClick(View.java:5204)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:21156)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5458)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-18 18:52:42.177  5586  5586 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-18 18:52:42.179  3138  3997 W ActivityManager:   Force finishing activity com.af.synapse/.MainActivity
09-18 18:52:42.255  3138  3184 W ProcessCpuTracker: Skipping unknown process pid 6557
09-18 18:52:42.261  3138  3184 W ProcessCpuTracker: Skipping unknown process pid 6603
09-18 18:52:42.261  3138  3184 W ProcessCpuTracker: Skipping unknown process pid 6605
09-18 18:52:42.271  3138  6609 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
09-18 18:52:42.272  3138  3188 W HardwareRenderer: Could not acquire gfx stats buffer
09-18 18:52:42.272  3138  3188 W HardwareRenderer: android.os.RemoteException: Invalid package name
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at com.android.server.GraphicsStatsService.requestBufferForProcess(GraphicsStatsService.java:97)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.ThreadedRenderer$ProcessInitializer.initGraphicsStats(ThreadedRenderer.java:459)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.ThreadedRenderer$ProcessInitializer.init(ThreadedRenderer.java:447)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.ThreadedRenderer.<init>(ThreadedRenderer.java:126)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.HardwareRenderer.create(HardwareRenderer.java:436)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.ViewRootImpl.enableHardwareAcceleration(ViewRootImpl.java:759)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.ViewRootImpl.setView(ViewRootImpl.java:492)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.app.Dialog.show(Dialog.java:319)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1470)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.os.Handler.dispatchMessage(Handler.java:102)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.os.Looper.loop(Looper.java:148)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at android.os.HandlerThread.run(HandlerThread.java:61)
09-18 18:52:42.272  3138  3188 W HardwareRenderer:  at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-18 18:52:42.313  3138  6609 I OpenGLRenderer: Initialized EGL, version 1.4
09-18 18:52:42.435  3138  3150 I art     : Background partial concurrent mark sweep GC freed 7440(687KB) AllocSpace objects, 12(336KB) LOS objects, 28% free, 10MB/14MB, paused 1.485ms total 215.270ms
09-18 18:52:42.724  3138  3184 W ActivityManager: Activity pause timeout for ActivityRecord{3eeb5f4 u0 com.af.synapse/.MainActivity t52 f}
09-18 18:52:42.781  3138  3184 I ActivityManager: Killing 4245:com.android.messaging/u0a57 (adj 15): empty #17
09-18 18:52:43.536  5586  5586 I Process : Sending signal. PID: 5586 SIG: 9
09-18 18:52:43.590  2044  3129 I chatty  : uid=1013(media) AudioOut_2 expire 12 lines
09-18 18:52:43.590  3138  3895 I libprocessgroup: Killing pid 5774 in uid 10055 as part of process group 5586
```

**Comment by arny24x7** [comment]
https://drive.google.com/file/d/0Bx_upRk6Kfw9MW1JanpEM3NEUHc/view?usp=sharing

full logcat
